### ISSUE TITLE
unique hashid 

### ISSUE THREAD

**Issue by Qasem-h** [dtaniwaki/acts_as_hashids#2]
does this gem generate unique hashid ?
and how i can save this ids into database ?

**Comment by Qasem-h** [comment]
@dtaniwaki

**Comment by dtaniwaki** [comment]
This gem generates invertible unique hash like ID. You don't have to store the generated hash in DB because you can get it from the original ID.

**Comment by Qasem-h** [comment]
@dtaniwaki Thank you for reply :+1:

**Comment by Qasem-h** [comment]
Hello @dtaniwaki 
Can i use hashid + freandly_id ? 
somthing like this :   site.com/hashid/slug 
Thank you

**Comment by supremebeing7** [comment]
@Qasem-h I don't see anything that would stop you from doing that. The purpose of both hashid and friendly_id is to allow for querying the db using something other than the integer id. Is there something in particular you are trying to accomplish by using both at the same time?

**Comment by dtaniwaki** [comment]
@supremebeing7 Thank you for the comment. I'm closing this issue because I also think we don't have to use it with friendly_id.
