### ISSUE TITLE
new version release?

### ISSUE THREAD

**Issue by spovich** [dtaniwaki/acts_as_hashids#23]
@dtaniwaki thank you for this gem and getting in the latest updates for Ruby 3.0/3.1 and Rails 6.1/7.0.  Any chance we can get a new version release?

My `Gemfile` has the latest version pinned with the github repo and reference, but we ran into an issue yesterday with Heroku where it failed to resolve `github.com` gems and blocked any releases.  It has been subsequently fixed by Heroku, but it would be helpful if we had a version bump published on rubygems.org.  Thank you!

**Comment by dtaniwaki** [comment]
https://rubygems.org/gems/acts_as_hashids/versions/0.2.0
Here you go! Sorry for the late reply.
